<?php

namespace AppBundle\Repository;

/**
 * ArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticulosRepository extends \Doctrine\ORM\EntityRepository
{
}
